name: medTalk
description:
  A Flutter project showcasing supported Material 3 components, typography, color system and elevation.
  Supports different light/dark mode, color seed, and comparison to Material 2.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.1.1
  avatar_glow:
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  syncfusion_flutter_datepicker: ^21.2.10
  logger:
  image_picker: ^0.8.8
  flutter_local_notifications: ^14.1.1
  timezone: ^0.9.0
  flutter_screenutil:



  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  syncfusion_flutter_sliders: ^21.2.6
  syncfusion_flutter_core: ^21.2.6
  get_storage:
  provider: ^6.0.5
  flutter_markdown: ^0.6.15
  animations: ^2.0.7
  shared_preferences: ^2.1.2
  local_auth: ^2.1.6
  flutter_datetime_picker: ^1.5.1
  flutter_native_splash: ^2.3.1
dev_dependencies:
#  analysis_defaults:
#    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_light.png
  color_dark: "#000000"
  image_dark: assets/images/logo_dark.png

  android_12:
    image: assets/images/logo_light.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo_dark.png
    icon_background_color_dark: "#000000"

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
